const cfg = window.APP_CONFIG || {};
const hasSupabase = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY;
const supabaseClient = hasSupabase ? supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
let currentUser = null, profile = null;
let charts = {};
const today = () => new Date().toISOString().slice(0,10);
const key = (name) => `nfe_${currentUser?.id || 'local'}_${name}`;
const $ = id => document.getElementById(id);
const money = n => Math.round(Number(n)||0);
function localGet(n, d){ try{return JSON.parse(localStorage.getItem(key(n))) ?? d}catch{return d} }
function localSet(n, v){ localStorage.setItem(key(n), JSON.stringify(v)); }
function show(el){ $(el).classList.remove('hidden') } function hide(el){ $(el).classList.add('hidden') }
function dateId(){return today()}
async function init(){
  buildLabInputs(); buildExerciseSelect(); document.querySelectorAll('#pName,#pAge,#pGender,#pHeight,#pWeight,#pActivity,#pGoal').forEach(e=>e.addEventListener('input',previewTargets));
  if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
  if(supabaseClient){ const {data:{session}}=await supabaseClient.auth.getSession(); currentUser=session?.user||null; supabaseClient.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null; boot();}); } else { currentUser={id:'local',email:'local'}; }
  boot();
}
async function boot(){ if(!currentUser){show('authScreen');hide('app');return;} hide('authScreen');show('app'); await loadProfile(); renderAll(); }
async function signInWithGoogle(){ if(!supabaseClient) return alert('Add Supabase URL and anon key in config.js first.'); await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}}); }
async function emailSignIn(){ const email=$('authEmail').value, password=$('authPassword').value; const {error}=await supabaseClient.auth.signInWithPassword({email,password}); if(error) alert(error.message); }
async function emailSignUp(){ const email=$('authEmail').value, password=$('authPassword').value; const {error}=await supabaseClient.auth.signUp({email,password}); if(error) alert(error.message); else alert('Check email if confirmation is enabled, then sign in.'); }
async function signOut(){ if(supabaseClient) await supabaseClient.auth.signOut(); else location.reload(); }
async function loadProfile(){
  if(supabaseClient){ const {data,error}=await supabaseClient.from('profiles').select('*').eq('user_id',currentUser.id).maybeSingle(); if(!error && data) profile=data; }
  if(!profile) profile=localGet('profile', null);
  if(!profile){ profile={name:'My Elder Profile',age:65,gender:'male',height:165,weight:70,activity:'1.2',goal:'elder-maintain',diet:'Mixed Indian + Global',cuisine:'Indian',conditions:['hypertension'],allergies:'',medicines:'',doctor_notes:'',emergency:''}; }
  fillProfile();
}
function selectedMulti(id){return [...$(id).selectedOptions].map(o=>o.value)}
function fillProfile(){ ['Name','Age','Gender','Height','Weight','Activity','Goal','Diet','Cuisine','Allergies','Medicines','DoctorNotes','Emergency'].forEach(x=>{const el=$('p'+x); if(el) el.value=profile[toSnake(x)]||profile[x.toLowerCase()]||''}); if(profile.conditions) [...$('pConditions').options].forEach(o=>o.selected=profile.conditions.includes(o.value)); previewTargets(); }
function toSnake(s){return s.replace(/[A-Z]/g,(m,i)=>(i?'_':'')+m.toLowerCase())}
function targets(){
  const age=+profile.age||30,h=+profile.height||170,w=+profile.weight||70,act=+profile.activity||1.2; let bmr=(profile.gender==='female')?10*w+6.25*h-5*age-161:10*w+6.25*h-5*age+5; let cal=Math.round(bmr*act); if(profile.goal==='loss')cal-=350; if(profile.goal==='gain')cal+=250; if(profile.goal==='elder-maintain')cal=Math.round(cal*.95); cal=Math.max(cal,1200); return {cal, protein:Math.round(w*(age>=60?1.1:1.4)), carbs:Math.round(cal*.45/4), fats:Math.round(cal*.28/9), fiber:age>=60?25:30, sodium:(profile.conditions||[]).includes('hypertension')?1500:2300, water:8, steps:age>=60?5000:8000};
}
function previewTargets(){ if(!profile)return; const t=targets(); $('targetPreview').innerHTML=`<b>Estimated daily targets:</b> ${t.cal} kcal • Protein ${t.protein}g • Carbs ${t.carbs}g • Fats ${t.fats}g • Fiber ${t.fiber}g • Sodium target < ${t.sodium}mg`; }
async function saveProfile(){
  profile={...(profile||{}), user_id:currentUser.id, name:$('pName').value, age:+$('pAge').value, gender:$('pGender').value, height:+$('pHeight').value, weight:+$('pWeight').value, activity:$('pActivity').value, goal:$('pGoal').value, diet:$('pDiet').value, cuisine:$('pCuisine').value, conditions:selectedMulti('pConditions'), allergies:$('pAllergies').value, medicines:$('pMedicines').value, doctor_notes:$('pDoctorNotes').value, emergency:$('pEmergency').value, updated_at:new Date().toISOString()};
  localSet('profile', profile); if(supabaseClient){ const {error}=await supabaseClient.from('profiles').upsert(profile,{onConflict:'user_id'}); if(error) alert('Cloud save error: '+error.message); }
  renderAll(); alert('Profile saved.');
}
function showTab(tab){ document.querySelectorAll('.tab-panel').forEach(p=>p.classList.add('hidden')); show(tab); document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); renderAll(); }
function getLogs(n){return localGet(n, [])} function setLogs(n,v){localSet(n,v)}
function todayItems(n){return getLogs(n).filter(x=>x.date===dateId())}
function calcFoodTotals(items=todayItems('foods')){return items.reduce((a,i)=>{a.cal+=+i.cal||0;a.p+=+i.p||0;a.c+=+i.c||0;a.f+=+i.f||0;a.fiber+=+i.fiber||0;a.sugar+=+i.sugar||0;a.sodium+=+i.sodium||0;return a},{cal:0,p:0,c:0,f:0,fiber:0,sugar:0,sodium:0})}
async function searchFood(){ const q=$('foodQuery').value.trim(); if(!q)return; const src=$('foodSource').value; $('foodResults').innerHTML='<p class="muted">Searching...</p>'; let results=[]; if(src==='all'||src==='local') results.push(...LOCAL_FOODS.filter(f=>(f.name+' '+f.group+' '+(f.tags||[]).join(' ')).toLowerCase().includes(q.toLowerCase())).map(f=>({...f,source:'Local'}))); if(src==='all'||src==='usda') results.push(...await searchUsda(q)); if(src==='all'||src==='off') results.push(...await searchOpenFoodFacts(q)); renderFoodResults(results.slice(0,30)); }
async function searchUsda(q){ try{const r=await fetch(`/api/usda?q=${encodeURIComponent(q)}`); if(!r.ok)return []; const d=await r.json(); return (d.foods||[]).map(f=>({name:f.description,group:f.foodCategory||'USDA',serving:'100g approx',cal:nutr(f,1008),p:nutr(f,1003),c:nutr(f,1005),f:nutr(f,1004),fiber:nutr(f,1079),sugar:nutr(f,2000),sodium:nutr(f,1093),source:'USDA'}));}catch{return []}}
function nutr(f,num){return +(f.foodNutrients||[]).find(n=>n.nutrientId===num)?.value||0}
async function searchOpenFoodFacts(q){ try{const r=await fetch(`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=10`); const d=await r.json(); return (d.products||[]).map(p=>{const n=p.nutriments||{}; return {name:p.product_name||p.generic_name||'Packaged food',group:p.brands||'Open Food Facts',serving:'100g / label',cal:n['energy-kcal_100g']||0,p:n.proteins_100g||0,c:n.carbohydrates_100g||0,f:n.fat_100g||0,fiber:n.fiber_100g||0,sugar:n.sugars_100g||0,sodium:Math.round((n.salt_100g||0)*400),source:'Open Food Facts'}}).filter(x=>x.name); }catch{return []}}
function renderFoodResults(arr){ $('foodResults').innerHTML=arr.length?arr.map((f,i)=>`<div class="result"><h3>${f.name}</h3><div class="meta"><span>${f.source||'Local'}</span><span>${f.group||''}</span><span>${f.serving||''}</span></div><p class="muted">${money(f.cal)} kcal • P ${money(f.p)}g • C ${money(f.c)}g • F ${money(f.f)}g • Fiber ${money(f.fiber)}g • Sodium ${money(f.sodium)}mg</p><label>Quantity multiplier<input id="fq${i}" type="number" value="1" step="0.25"></label><button onclick='addFood(${JSON.stringify(f).replaceAll("'","&#39;")},"fq${i}")'>Add to ${$('mealType').value}</button></div>`).join(''):'<p class="muted">No result. Try a simpler food name or local ingredient.</p>'; }
function addFood(f,qid){const q=+$(`${qid}`).value||1; const logs=getLogs('foods'); logs.push({...f, date:dateId(), meal:$('mealType').value, qty:q, cal:f.cal*q,p:f.p*q,c:f.c*q,f:f.f*q,fiber:f.fiber*q,sugar:f.sugar*q,sodium:f.sodium*q}); setLogs('foods',logs); renderAll();}
function removeLog(type,idx){const l=getLogs(type); l.splice(idx,1); setLogs(type,l); renderAll();}
function renderMeals(){const items=todayItems('foods'); $('mealLog').innerHTML=items.length?items.map((x,i)=>`<div class="log"><div class="row-between"><div><h3>${x.meal}: ${x.name}</h3><p class="muted">${money(x.cal)} kcal • P ${money(x.p)}g C ${money(x.c)}g F ${money(x.f)}g • qty ${x.qty}</p></div><button class="danger" onclick="removeLog('foods',${getLogs('foods').indexOf(x)})">Remove</button></div></div>`).join(''):'<p class="muted">No meals logged today.</p>';}
function quickWater(){const v=todayItems('vitals')[0]||{date:dateId()}; v.water=(+v.water||0)+1; upsertToday('vitals',v); renderAll();} function quickSteps(){const v=todayItems('vitals')[0]||{date:dateId()}; v.steps=(+v.steps||0)+1000; upsertToday('vitals',v); renderAll();}
function upsertToday(type,obj){const l=getLogs(type); const i=l.findIndex(x=>x.date===dateId()); if(i>=0)l[i]={...l[i],...obj}; else l.push(obj); setLogs(type,l)}
function saveVitals(){const v={date:dateId(), systolic:+$('vSys').value||0, diastolic:+$('vDia').value||0, pulse:+$('vPulse').value||0, glucose:+$('vGlucose').value||0, weight:+$('vWeight').value||0, sleep:+$('vSleep').value||0, steps:+$('vSteps').value||0, pain:+$('vPain').value||0, mood:$('vMood').value, meds:$('vMeds').value, bowel:$('vBowel').value, water:+$('vWater').value||0, notes:$('vNotes').value}; upsertToday('vitals',v); renderAll(); alert('Health check saved.');}
function renderVitals(){const v=getLogs('vitals').slice(-10).reverse(); $('vitalList').innerHTML=v.length?v.map(x=>`<div class="log ${classForVitals(x)}"><h3>${x.date}</h3><p class="muted">BP ${x.systolic||'-'}/${x.diastolic||'-'} • Sugar ${x.glucose||'-'} • Pulse ${x.pulse||'-'} • Sleep ${x.sleep||'-'}h • Pain ${x.pain??'-'}/10 • Meds ${x.meds||'-'}</p><p>${x.notes||''}</p></div>`).join(''):'<p class="muted">No health checks yet.</p>';}
function classForVitals(v){ if(v.systolic>=160||v.diastolic>=100||v.glucose>=250||v.pain>=8)return'alert'; if(v.systolic>=140||v.diastolic>=90||v.glucose>=126||v.pain>=5)return'warn'; return'ok';}
function buildLabInputs(){ $('labInputs').innerHTML=Object.entries(HEALTH_RULES.markers).map(([k,m])=>`<label>${m.label} (${m.unit})<input id="lab_${k}" type="number" step="0.01"></label>`).join('')+`<label class="wide">Lab note<textarea id="labNote"></textarea></label>`; $('reportDate').value=dateId(); }
async function saveReport(){ const file=$('reportFile').files[0]||$('cameraFile').files[0]; const rec={date:$('reportDate').value||dateId(), type:$('reportType').value, notes:$('reportNotes').value, fileName:file?.name||'No file', fileUrl:''}; if(file&&supabaseClient){const path=`${currentUser.id}/${Date.now()}-${file.name}`; const {error}=await supabaseClient.storage.from('health-reports').upload(path,file,{upsert:false}); if(error) alert('Upload failed: '+error.message); else rec.fileUrl=path;} const logs=getLogs('reports'); logs.push(rec); setLogs('reports',logs); renderAll(); alert(file&&supabaseClient?'Report uploaded.':'Report saved. For cloud file upload, configure Supabase storage.'); }
function saveLabs(){ const values={date:$('reportDate').value||dateId(), note:$('labNote').value}; Object.keys(HEALTH_RULES.markers).forEach(k=>{const val=+$(`lab_${k}`).value; if(val) values[k]=val;}); const logs=getLogs('labs'); logs.push(values); setLogs('labs',logs); renderAll(); alert('Lab values saved.'); }
function renderReports(){const reports=getLogs('reports').slice().reverse(); const labs=getLogs('labs').slice().reverse(); $('reportList').innerHTML=reports.length?reports.map(r=>`<div class="log"><h3>${r.type} — ${r.date}</h3><p class="muted">${r.fileName}</p><p>${r.notes||''}</p></div>`).join(''):'<p class="muted">No reports uploaded yet.</p>'; $('labList').innerHTML=labs.length?labs.map(l=>`<div class="log"><h3>Lab values — ${l.date}</h3>${Object.entries(l).filter(([k,v])=>HEALTH_RULES.markers[k]).map(([k,v])=>`<p class="muted">${HEALTH_RULES.markers[k].label}: <b>${v} ${HEALTH_RULES.markers[k].unit}</b> — ${labStatus(k,v)}</p>`).join('')}<p>${l.note||''}</p></div>`).join(''):'';}
function labStatus(k,v){const m=HEALTH_RULES.markers[k]; if(m.review && ((m.low&&v<m.review)||(m.high&&v>=m.review)))return'Review with doctor'; if(m.low&&v<m.low)return'Below common range'; if(m.high&&v>m.high)return'Above common range'; return'Within common target/range';}
function buildExerciseSelect(){ $('exSelect').innerHTML=EXERCISES.map((e,i)=>`<option value="${i}">${e.name} (${e.minutes} min)</option>`).join(''); }
function renderExercisePlan(){const cond=profile.conditions||[]; let list=EXERCISES.filter(e=>e.elderSafe); if(cond.includes('arthritis')) list=list.filter(e=>['Chair exercise','Mobility','Balance','Relaxation','Cardio'].includes(e.type)); $('exercisePlan').innerHTML=list.map(e=>`<div class="exercise"><h3>${e.name}</h3><div class="meta"><span>${e.type}</span><span>${e.level}</span><span>${e.minutes} min</span></div><p class="muted">${e.notes}</p><a href="${e.video}" target="_blank"><button class="secondary">Open video options</button></a></div>`).join(''); const logs=getLogs('exercise').slice(-10).reverse(); $('exerciseLog').innerHTML=logs.length?logs.map(x=>`<div class="log"><h3>${x.name}</h3><p class="muted">${x.date} • ${x.minutes} min • ${x.effort} • approx ${money(x.calories)} kcal</p></div>`).join(''):'<p class="muted">No exercise logged yet.</p>';}
function saveExercise(){const e=EXERCISES[$('exSelect').value]; const mins=+$('exMinutes').value||e.minutes; const cal=(e.met*3.5*(+profile.weight||70)/200)*mins; const logs=getLogs('exercise'); logs.push({date:dateId(), name:e.name, minutes:mins, effort:$('exEffort').value, calories:cal}); setLogs('exercise',logs); renderAll();}
function renderDashboard(){const t=targets(), totals=calcFoodTotals(), vital=todayItems('vitals')[0]||{}; $('dashName').textContent=profile.name||'Profile'; $('calConsumed').textContent=money(totals.cal); $('proteinConsumed').textContent=money(totals.p)+'g'; $('waterCount').textContent=vital.water||0; $('stepsCount').textContent=vital.steps||0; $('calorieProgress').style.width=Math.min(100,totals.cal/t.cal*100)+'%'; const score=calcScore(totals,t,vital); $('nutritionScore').textContent=score; $('scoreText').textContent=score>=80?'Great balanced day':score>=55?'Good progress, continue tracking':score>0?'Needs improvement':'Start tracking meals and vitals'; $('safeTips').textContent='Quick tip: for elders, gentle consistency matters more than intensity.'; renderRecs(totals,t,vital); renderCharts(totals,t); }
function calcScore(a,t,v){ if(!a.cal&&!v.steps&&!v.water)return 0; let s=0; if(a.cal>t.cal*.75&&a.cal<t.cal*1.15)s+=25; else if(a.cal)s+=12; if(a.p>=t.protein*.75)s+=20; else if(a.p)s+=8; if(a.fiber>=t.fiber*.7)s+=15; if(a.sodium&&a.sodium<t.sodium)s+=10; if((v.water||0)>=6)s+=10; if((v.steps||0)>=t.steps*.7)s+=10; if(v.meds==='Yes')s+=10; return Math.min(100,s);}
function renderRecs(a,t,v){const rec=[]; if(a.p<t.protein*.7)rec.push(['Protein focus','Add dal, curd, paneer, egg, fish/chicken, Greek yogurt, or beans based on diet preference.']); if(a.fiber<t.fiber*.6)rec.push(['Fiber focus','Add vegetables, guava/apple, oats, dal, beans, brown rice, jowar/bajra in controlled portions.']); if(a.sodium>t.sodium)rec.push(['Low sodium day needed','Reduce packaged snacks, pickles, papad, salty namkeen, and restaurant food.']); if((v.water||0)<6)rec.push(['Hydration','Add water reminders unless doctor has fluid restriction.']); (profile.conditions||[]).forEach(c=>(HEALTH_RULES.dietByCondition[c]||[]).slice(0,2).forEach(x=>rec.push([c.toUpperCase(),x]))); $('recommendations').innerHTML=rec.length?rec.map(r=>`<div class="rec"><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join(''):'<p class="muted">No suggestions yet. Add meals, vitals, and reports.</p>';}
function renderCharts(a,t){ const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d.toISOString().slice(0,10)}); const allFood=getLogs('foods'); const cals=days.map(d=>allFood.filter(x=>x.date===d).reduce((s,x)=>s+(+x.cal||0),0)); const vit=getLogs('vitals'); const sys=days.map(d=>vit.find(x=>x.date===d)?.systolic||null); makeChart('macroChart','doughnut',{labels:['Protein','Carbs','Fats'],datasets:[{data:[a.p*4,a.c*4,a.f*9]}]}); makeChart('calorieChart','line',{labels:days.map(d=>d.slice(5)),datasets:[{label:'Calories',data:cals},{label:'Target',data:days.map(()=>t.cal)}]}); makeChart('vitalChart','line',{labels:days.map(d=>d.slice(5)),datasets:[{label:'Systolic BP',data:sys}]});}
function makeChart(id,type,data){ if(charts[id]) charts[id].destroy(); charts[id]=new Chart($(id),{type,data,options:{responsive:true,plugins:{legend:{labels:{color:'#cbd5e1'}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#93a4bc'},grid:{color:'#1f2d44'}},y:{ticks:{color:'#93a4bc'},grid:{color:'#1f2d44'}}}}});}
async function syncNow(){ await saveProfile(); alert('Profile saved. Daily logs are local in this starter. Next step: add Supabase log tables sync.');}
function renderAll(){ if(!profile)return; fillProfile(); renderDashboard(); renderMeals(); renderVitals(); renderReports(); renderExercisePlan(); }
init();
